function out = VisemeCorpus
% out = VisemeCorpus
%
% maps ARPAbet phonemes into 12 percetually equivalent viseme groups.
%
% Based on:
% Auer, E.T, Bernstein, L.E., 1997. Speechreading and the structure of the
% lexicon: Computationally modeling the effects of reduced phonetic
% distinctiveness on lexical uniqueness. J. Acoust. Soc. Am. 102, 370

Corpus = {...
    {'UH', 'UW', 'AXR', 'ER'}, ...
    {'AW', 'OW'}, ...
    {'IH', 'IY', 'EH', 'AE', 'EY'}, ...
    {'OY'}, ...
    {'AO', 'AY', 'AX', 'AA', 'AH', 'Y'}, ...
    {'B', 'P', 'M'}, ...
    {'F', 'V'}, ...
    {'L', 'N', 'K', 'NG', 'G', 'HH', 'H'}, ...
    {'D', 'T', 'S', 'Z'}, ...
    {'W', 'DX', 'R'}, ...
    {'DH', 'TH'}, ...
    {'SH', 'CH', 'ZH', 'JH'}, ...
    };

out = Corpus;

end